# Configuration for object detection node
/object_det:
  ros__parameters:
    # print debug output
    debug: true
    # rotate images?
    rotation: 0
    # image source topic
    topic: "/background/color_small_limited"
    image_size: 640
    print_detections: false
    print_fps: true
    det_topic: "/object_det/objects"
    fps_topic: "/object_det/fps"
    power_topic: "/object_det/hailo8/avg_power"
    max_fps: 30.0
    # Use sensor data Quality of Service for messages
    qos_sensor_data: true
    # Message queue size
    qos_history_depth: 5
    ### --------------- ###
    # YOLO STUFF
    YOLOV7_HEF_FILE: "/opt/dev/DL_Models/yolo_object/model/yolov7.hef"
    CLASS_FILE: "/opt/dev/DL_Models/yolo_object/data/coco.names"
    DETECT_STR: "DETECTED_OBJECTS"
    AMOUNT_STR: "DETECTED_OBJECTS_AMOUNT"
    FPS_STR: "OBJECT_DET_FPS"
    deviceID: "0004:01:00.0"
    YOLO_THRESHOLD: 0.35
    YOLO_Anchor: "{{ 142, 110, 192, 243, 459, 401 }, { 36, 75, 76, 55, 72, 146 }, { 12, 16, 19, 36, 40, 28 }}"



# Configuration for gesture detection node
/gesture_det:
  ros__parameters:
    # print debug output
    debug: true
    # rotate images?
    rotation: 0    
    # image source topic
    topic: "/background/color_small_limited"
    image_size: 640
    print_detections: false
    print_fps: true
    det_topic: "/gesture_det/gestures"
    fps_topic: "/gesture_det/fps"
    power_topic: "/gesture_det/hailo8/avg_power"
    max_fps: 30.0
    # Use sensor data Quality of Service for messages
    qos_sensor_data: true
    # Message queue size
    qos_history_depth: 5

    ### --------------- ###
    # YOLO STUFF
    CLASS_FILE: "/opt/dev/DL_Models/yolo_human/data/hand_set.names"
    YOLOV7_HEF_FILE: "/opt/dev/DL_Models/yolo_human/model/yolov7_gesture.hef"
    DETECT_STR: "DETECTED_GESTURES"
    AMOUNT_STR: "DETECTED_GESTURES_AMOUNT"
    FPS_STR: "GESTURE_DET_FPS"
    deviceID: "0001:01:00.0"
    YOLO_THRESHOLD: 0.35
    YOLO_Anchor: "{{ 228, 335, 301, 338, 233, 513 }, { 73, 90, 107, 111, 168, 365 }, { 34, 54, 58, 70, 49, 97 }}"

    
